apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pyroscope
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "12"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: bootstrap
  source:
    repoURL: https://grafana.github.io/helm-charts
    chart: pyroscope
    targetRevision: 2.0.1
    helm:
      releaseName: pyroscope
      valuesObject:
        pyroscope:
          replicaCount: 1
          disableSelfProfile: false
          persistence:
            enabled: true
            size: 10Gi
          service:
            type: ClusterIP
          resources:
            requests:
              cpu: 100m
              memory: 512Mi
            limits:
              memory: 1Gi
        ingress:
          enabled: false
        minio:
          enabled: false
  destination:
    server: https://kubernetes.default.svc
    namespace: observability
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
